// DR Børneserier - Hardcoded EntityIds

export interface DRSeries {
  entityId: string;
  title: string;
  slug: string;
  seasons?: number;
  ageMin?: number;
  ageMax?: number;
  description?: string;
  isNordic?: boolean; // Nordisk vs rent dansk
}

export const DR_CHILDREN_SERIES: DRSeries[] = [
  // DANSK FIKTION
  {
    entityId: '6534',
    title: 'Motor Mille og Børnebanden',
    slug: 'motor-mille',
    seasons: 3,
    ageMin: 4,
    ageMax: 8,
  },
  {
    entityId: '6535',
    title: 'Sprinter Galore',
    slug: 'sprinter-galore',
    seasons: 4,
    ageMin: 5,
    ageMax: 10,
  },
  {
    entityId: '434949',
    title: 'Den magiske klub',
    slug: 'den-magiske-klub',
    seasons: 2,
    ageMin: 6,
    ageMax: 10,
  },
  {
    entityId: '7347',
    title: 'Onkel Rejes Sørøvershow',
    slug: 'onkel-reje-soerovershow',
    seasons: 2,
    ageMin: 3,
    ageMax: 7,
  },
  {
    entityId: '340992',
    title: 'Heksebeth',
    slug: 'heksebeth',
    seasons: 1,
    ageMin: 5,
    ageMax: 9,
  },
  {
    entityId: '472268',
    title: 'Heksebeth og den hovedløse magi',
    slug: 'heksebeth-hovedlose-magi',
    seasons: 1,
    ageMin: 5,
    ageMax: 9,
  },
  {
    entityId: '463560',
    title: 'Klar, parat, skolestart',
    slug: 'klar-parat-skolestart',
    seasons: 2,
    ageMin: 5,
    ageMax: 7,
  },
  {
    entityId: '456515',
    title: 'HundeBanden',
    slug: 'hundebanden',
    seasons: 2,
    ageMin: 5,
    ageMax: 10,
  },
  {
    entityId: '296793',
    title: 'Max Pinlig',
    slug: 'max-pinlig',
    seasons: 2,
    ageMin: 8,
    ageMax: 12,
  },
  {
    entityId: '35340',
    title: 'Oda Omvendt',
    slug: 'oda-omvendt',
    seasons: 2,
    ageMin: 6,
    ageMax: 10,
  },
  {
    entityId: '509125',
    title: 'Skattejagten',
    slug: 'skattejagten',
    seasons: 1,
    ageMin: 6,
    ageMax: 10,
  },
  {
    entityId: '416471',
    title: 'Jagten på regnbuens magi',
    slug: 'jagten-regnbuens-magi',
    seasons: 1,
    ageMin: 5,
    ageMax: 9,
  },
  {
    entityId: '480849',
    title: 'Jagten på regnbuens eliksir',
    slug: 'jagten-regnbuens-eliksir',
    seasons: 1,
    ageMin: 5,
    ageMax: 9,
  },
  {
    entityId: '410241',
    title: 'Hugo og Drømmemasken',
    slug: 'hugo-droemmemasken',
    seasons: 1,
    ageMin: 4,
    ageMax: 8,
  },
  {
    entityId: '122550',
    title: 'Far, Mor og Bjørn',
    slug: 'far-mor-bjorn',
    seasons: 1,
    ageMin: 3,
    ageMax: 6,
  },
  {
    entityId: '157304',
    title: 'Osman og Jeppe',
    slug: 'osman-og-jeppe',
    seasons: 2,
    ageMin: 6,
    ageMax: 10,
  },
  {
    entityId: '426014',
    title: 'Onkel Reje og Galaksens Helte',
    slug: 'onkel-reje-galaksen',
    seasons: 1,
    ageMin: 3,
    ageMax: 7,
  },
  {
    entityId: '67094',
    title: 'Onkel Rejes Heavyband',
    slug: 'onkel-reje-heavyband',
    seasons: 1,
    ageMin: 3,
    ageMax: 7,
  },
  {
    entityId: '489440',
    title: 'Det sidste nye med Onkel Reje',
    slug: 'sidste-nye-onkel-reje',
    seasons: 1,
    ageMin: 3,
    ageMax: 7,
  },
  {
    entityId: '69736',
    title: 'Paphoved',
    slug: 'paphoved',
    seasons: 1,
    ageMin: 4,
    ageMax: 8,
  },
  {
    entityId: '128190',
    title: 'Cirkusliv i savsmuld',
    slug: 'cirkusliv-savsmuld',
    seasons: 1,
    ageMin: 5,
    ageMax: 9,
  },
  {
    entityId: '140053',
    title: 'Bella Boris og Berta',
    slug: 'bella-boris-berta',
    seasons: 1,
    ageMin: 3,
    ageMax: 6,
  },
  {
    entityId: '390674',
    title: 'Elefantvask',
    slug: 'elefantvask',
    seasons: 1,
    ageMin: 2,
    ageMax: 5,
  },
  {
    entityId: '101437',
    title: 'Bobbel og Gælles Mission',
    slug: 'bobbel-gaelle',
    seasons: 1,
    ageMin: 4,
    ageMax: 8,
  },

  // NORDISK FIKTION
  {
    entityId: '395829',
    title: 'Brandbamsen Bjørnis',
    slug: 'brandbamsen-bjornis',
    seasons: 2,
    ageMin: 2,
    ageMax: 5,
    isNordic: true,
  },
  {
    entityId: '152187',
    title: 'Pippi Langstrømpe',
    slug: 'pippi-langstrompe',
    seasons: 1,
    ageMin: 4,
    ageMax: 10,
    isNordic: true,
  },
  {
    entityId: '238547',
    title: 'Kasper og Sofie',
    slug: 'kasper-og-sofie',
    seasons: 4,
    ageMin: 4,
    ageMax: 8,
    isNordic: true,
  },
  {
    entityId: '322610',
    title: 'Superhelteskolen',
    slug: 'superhelteskolen',
    seasons: 2,
    ageMin: 6,
    ageMax: 10,
    isNordic: true,
  },
  {
    entityId: '513681',
    title: 'Agenterne',
    slug: 'agenterne',
    seasons: 1,
    ageMin: 7,
    ageMax: 11,
    isNordic: true,
  },
  {
    entityId: '533781',
    title: 'Mini-agenterne',
    slug: 'mini-agenterne',
    seasons: 1,
    ageMin: 5,
    ageMax: 9,
    isNordic: true,
  },
  {
    entityId: '308118',
    title: 'Stop!',
    slug: 'stop',
    seasons: 4,
    ageMin: 6,
    ageMax: 10,
    isNordic: true,
  },
  {
    entityId: '306782',
    title: 'Trex',
    slug: 'trex',
    seasons: 1,
    ageMin: 5,
    ageMax: 9,
    isNordic: true,
  },
  {
    entityId: '355800',
    title: 'Restaurant Million',
    slug: 'restaurant-million',
    seasons: 1,
    ageMin: 6,
    ageMax: 10,
    isNordic: true,
  },
  {
    entityId: '207815',
    title: 'Søskende-chok',
    slug: 'soskende-chok',
    seasons: 1,
    ageMin: 7,
    ageMax: 11,
    isNordic: true,
  },
  {
    entityId: '306783',
    title: 'Vesta-Linnea',
    slug: 'vesta-linnea',
    seasons: 1,
    ageMin: 5,
    ageMax: 9,
    isNordic: true,
  },
  {
    entityId: '6663',
    title: 'Elsa',
    slug: 'elsa',
    seasons: 1,
    ageMin: 4,
    ageMax: 8,
    isNordic: true,
  },
  {
    entityId: '132265',
    title: 'Sol snart 6 år',
    slug: 'sol-snart-6',
    seasons: 1,
    ageMin: 4,
    ageMax: 7,
    isNordic: true,
  },
  {
    entityId: '133553',
    title: 'Hanna og Rally',
    slug: 'hanna-og-rally',
    seasons: 1,
    ageMin: 4,
    ageMax: 8,
    isNordic: true,
  },
  {
    entityId: '149627',
    title: 'Kevin og farfar',
    slug: 'kevin-og-farfar',
    seasons: 1,
    ageMin: 4,
    ageMax: 8,
    isNordic: true,
  },
  {
    entityId: '149622',
    title: 'Sommeren med far',
    slug: 'sommeren-med-far',
    seasons: 1,
    ageMin: 5,
    ageMax: 9,
    isNordic: true,
  },
  {
    entityId: '149626',
    title: 'Men Kasper da',
    slug: 'men-kasper-da',
    seasons: 1,
    ageMin: 4,
    ageMax: 8,
    isNordic: true,
  },
  {
    entityId: '149634',
    title: 'Mysteriebureauet',
    slug: 'mysteriebureauet',
    seasons: 1,
    ageMin: 6,
    ageMax: 10,
    isNordic: true,
  },

  // SPECIELLE / JULE
  {
    entityId: '555196',
    title: 'Bamses Julerejse',
    slug: 'bamses-julerejse',
    seasons: 1,
    ageMin: 3,
    ageMax: 7,
  },
  {
    entityId: '507846',
    title: 'Det store Ramasjang Mysterie',
    slug: 'ramasjang-mysterie',
    seasons: 1,
    ageMin: 5,
    ageMax: 9,
  },
  {
    entityId: '171280',
    title: 'Det Kongelige Spektakel',
    slug: 'kongelige-spektakel',
    seasons: 1,
    ageMin: 6,
    ageMax: 10,
  },
];
